### ISSUE TITLE
Constant speed

### ISSUE THREAD

**Issue by poyraz-birusk** [pkerspe/ESP-FlexyStepper#27] opened 2022-03-16 22:09 UTC
Sorry since this is rather a question, I was wondering how it would be to control a stepper speed without any position information. If I want to run the speed constantly with for example using speedInMillimetersPerSecond or speedInRevolutionsPerSecond

**Comment by pkerspe** [comment] 2022-03-18 14:56
what you are looking for is the Jogging function, this is a duplicate of the feature Request #16

**Closed as completed** 2022-03-18 14:57 UTC
Labels: duplicate
